version: '3'
services:
  mysqlbackup:
    image: zelejs/mysqlbackup
    container_name: mysqlbackup
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mysql_backup/data:/var/mysqlbackup/data
      - ./mysql_backup/log:/var/mysqlbackup/log
      - ./mysql_backup/backup_api:/backup_api
      - ./mysql_backup/crond.sh:/usr/local/bin/crond.sh
      - ./mysql_backup/db-diff.sh:/usr/local/bin/db-diff.sh
      - ./mysql_backup/note.json:/usr/local/bin/note.json
    environment:
      MYSQL_DB: cinema
      #TZ: "Asia/Shanghai"
      MYSQL_HOST: 192.168.3.236
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_USER_PASSWORD: root
      CRONTAB_DAILY_HOUR: 2
      CRONTAB_DAILY_MIN: 15
      # 远端基础信息
      DIFF_REMOTE: xingyu.cloud.smallsaas.cn
      # 本地基础信息
      DIFF_LOCAL: 192.168.3.236
      # 数据端口
      DIFF_REMOTE_PORT: 3306
      # 数据端口
      DIFF_LOCAL_PORT: 3306
      # 远程对比数据库
      DIFF_REMOTE_DB: cinema
      # 本地对比数据库
      DIFF_LOCAL_DB: cinema
      # 远程数据库用户
      DIFF_REMOTE_DB_USER: root
      # 本地数据库用户
      DIFF_LOCAL_DB_USER: root
      # 远程数据库密钥
      DIFF_REMOTE_DB_PWD: rootAZaz@123
      # 本地数据库密钥
      DIFF_LOCAL_DB_PWD: root
      # ip@port@user@password@database@table
      # TEST_ENV: 172.0.0.3@3306@root@root@test@cr_issue_task
      # PROD_ENV: 172.0.0.2@3306@root@zxcABC123@cinema@cr_issue_task
networks:
  default:
    external:
      name: sandbox_cinema_default
