version: '3'
services:
  mysqlbackup:
    image: zelejs/mysqlbackup
    container_name: mysqlbackup
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mysql_backup/data:/var/mysqlbackup/data
      - ./mysql_backup/log:/var/mysqlbackup/log
      - ./mysql_backup/backup_api:/backup_api
      - ./mysql_backup/crond.sh:/usr/local/bin/crond.sh
      - ./mysql_backup/db-diff.sh:/usr/local/bin/db-diff.sh
    environment:
      MYSQL_DB: some_db
      #TZ: "Asia/Shanghai"
      MYSQL_HOST: 172.17.0.1
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_USER_PASSWORD: root
      CRONTAB_DAILY_HOUR: 2
      CRONTAB_DAILY_MIN: 15
      MYDIFF_ORIGIN_REMOTE: xing@xingyu.cloud.cn:pw
      MYDIFF_ORIGIN_DATA: mysqlserver:3306/dbname[cr_issue_task]
      MYDIFF_DATA: mysqlserver:3306/dbname[cr_issue_task]
      MYDIFF_ORIGIN_DATA_USER: root
      MYDIFF_DATA_USER: root
      MYDIFF_ORIGIN_DATA_PASSWORD: root
      MYDIFF_DATA_PASSWORD: zxcABC123
      # ip@port@user@password@database@table
      # TEST_ENV: 172.0.0.3@3306@root@root@test@cr_issue_task
      # PROD_ENV: 172.0.0.2@3306@root@zxcABC123@cinema@cr_issue_task
